# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : NJAUMC
tagline: THE camp
author :
  name : Colin Chang
  email : colinichang@gmail.com

css:
  - /assets/bootstrap/css/bootstrap.min.css
  - /assets/css/styles.css
js:
 - //ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"  
 - /assets/bootstrap/js/bootstrap.min.js

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: http://njaumc.github.com
baseurl: /

director_desc:
  darrell: /contents/Darrell_description.md
director_pic: 
  darrell: /assets/img/juniorhighcamp/People_Darrell.jpeg
  justin: /assets/img/juniorhighcamp/People_Justin.jpg
  darin: /assets/img/juniorhighcamp/People_Darin.jpg
  ryan: /assets/img/juniorhighcamp/People_Ryan.png
  kirk: /assets/img/juniorhighcamp/People_Kirk.jpg

junior_high_camp: /juniorhighcamp
asian_camp: /asiancamp
alpha_omega: /alphaomega
about: /about.html

asian_camp_counselor_app: /assets/docs/AC2013CounselorApp.pdf
junior_high_camp_docs:
  camper_reg: /assets/docs/JHCCamperRegistrationForm2013.pdf
  counselor_reg: /assets/docs/CounselorApplication2013.pdf

junior_high_camp_img:
  index: "/assets/img/juniorhighcamp/index.jpg"
asian_camp_img:
  index: /assets/img/asiancamp/42445-superhero.jpg
alpha_omega_img:
  index: /assets/img/alphaomega/sky.jpg